name: Build with Gradle

on:
    push:
        branches: '*'
        paths-ignore:
            - 'README.md'
            - 'LICENSE'
            - '.gitignore'
            - '.gitattributes'
            - '.editorconfig'
    pull_request:
        branches: '*'
        paths-ignore:
            - 'README.md'
            - 'LICENSE'
            - '.gitignore'
            - '.gitattributes'
            - '.editorconfig'

concurrency:
    # Maximum of one running wrokflow per pull request on source branches.
    # Cancel an old run if an action is re-run. 
    group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
    cancel-in-progress: true
    
jobs:
    build:
        name: "Build"
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v2
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v2
              with:
                    distribution: "temurin"
                    java-version: "17"
            - uses: actions/cache@v2
              with:
                    path: |
                        $HOME/.gradle/caches
                        $HOME/.gradle/wrapper
                    key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                    restore-keys: ${{ runner.os }}-gradle-
            - run: chmod +x ./gradlew
            - run: ./gradlew --no-daemon build
            
            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v2
              with:
                    name: NSE-jars
                    path: |
                        NotSoEssential-Fabric/build/libs/
                        NotSoEssential-Forge/build/libs/
